version: '2'

services:

    lamp:
        env_file: .env
        build: ./lamp
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        ports:
            - "80:80"

    mysql:
        env_file: .env
        build: ./mysql
        expose:
            - "3306"
        volumes:
            - ./db:/var/lib/mysql/
